---
#Make sure server is availabe and service is not running

  - name:  ping all servers
    ping:

  - name: Stop Tomcat
    command: sh /opt/tomcat8/bin/shutdown.sh
    # when: ansible_distribution == "Ubuntu"

  - name: Remove Tomcat
    file:
      path: /opt/tomcat8
      state: absent

  - name: remove user "tomcat"
    user:
      name: tomcat
      state: absent

  - name: remove group "tomcat"
    group:
      name: tomcat
      state: absent