---
  # - name: Configure Tomcat and Deploy application to target servers
  #   hosts: all
  #   become: true

  #   tasks:
  - name: Copy Tomcat service from local to remote
    copy:
      src: externalfiles/tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
      mode: 0755
