---
  # - name: Configure Tomcat and Deploy application to target servers
  #   hosts: all
  #   become: true

  #   tasks:
  - name: Copy Tomcat service from local to ubuntu remote
    copy:
      src: externalfiles/tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
      mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: Copy Tomcat service from local to CentOS remote
    copy:
      src: externalfiles/centos.tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
      mode: 0755
    when: ansible_distribution == "CentOS"
